// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: TruncateUsers.sql

package database

import (
	"context"
)

const truncateUsers = `-- name: TruncateUsers :exec
TRUNCATE TABLE users CASCADE
`

func (q *Queries) TruncateUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateUsers)
	return err
}
